apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.volc.bytedance.com
spec:
  group: volc.bytedance.com
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              version:
                type: string
          status:
            type: object
            properties:
              code: success
              message:
                type: string
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: mysqls
    singular: mysql
    kind: MySQL
